name: Generate README
on:
  workflow_dispatch: # Isse aap GitHub UI se manually run kar sakenge
  push:
    branches:
      - master

jobs:
  readme-ai:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install and Run README AI
        env:
          # OpenRouter API Key
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # OpenRouter ka Base URL set karna zaroori hai
          OPENAI_BASE_URL: "https://openrouter.ai/api/v1"
        run: |
          pip install readmeai
          # Model ka naam specify karna pad sakta hai agar default kaam na kare
          readmeai --repository . --api openai --model nvidia/nemotron-3-ultra-550b-a55b:free
