name: Generate README
on:
  push:
    branches:
      - main

jobs:
  readme-ai:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install and Run README AI
        run: |
          pip install readmeai
          readmeai --repository ${{ github.repository }} --api-key ${{ secrets.OPENAI_API_KEY }}
